-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Linked to Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  role text check (role in ('admin', 'doctor')) default 'doctor',
  created_at timestamptz default now()
);

-- Trigger to create profile on signup
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'doctor');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. CATEGORIES
create table public.categories (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  description text,
  created_at timestamptz default now()
);

-- Seed Categories
insert into public.categories (name) values 
('Consulta'), ('Vacunación'), ('Cirugía'), ('Farmacia'), ('Alimento'), ('Hallezgo');

-- 3. INVOICES (Encabezados)
create table public.invoices (
  id uuid default uuid_generate_v4() primary key,
  ticket_numero int GENERATED BY DEFAULT AS IDENTITY, -- Human readable ID
  fecha_venta date default current_date,
  forma_pago text,
  subtotal_q numeric(10,2),
  total_q numeric(10,2),
  pagado_q numeric(10,2),
  cambio_q numeric(10,2),
  doctor_id uuid references public.profiles(id),
  observaciones_doctora text,
  file_url text, -- Link to uploaded file
  status text check (status in ('draft', 'confirmed')) default 'draft', -- draft = n8n processed, pending review
  processed_by_n8n boolean default false,
  raw_ocr_data jsonb, -- Backup of full n8n response
  consistency_has_inconsistencies boolean default false,
  created_at timestamptz default now()
);

-- 4. INVOICE ITEMS (Detalles)
create table public.invoice_items (
  id uuid default uuid_generate_v4() primary key,
  invoice_id uuid references public.invoices(id) on delete cascade,
  descripcion text,
  cantidad numeric(10,2),
  precio_unitario_q numeric(10,2),
  total_q numeric(10,2),
  comisionable boolean default false,
  categoria_id uuid references public.categories(id),
  created_at timestamptz default now()
);

-- RLS POLICIES (Simplified for dev speed)

alter table public.profiles enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

-- Profiles: Read all (for assigning), Update own
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Invoices: 
-- Admin sees all. 
-- Doctors see only their own invoices.
create policy "Admins see all invoices" on public.invoices 
  for all using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Doctors see own invoices" on public.invoices
  for all using (
    doctor_id = auth.uid()
  );

-- Invoice Items: Inherit Invoice policy
create policy "Admins see all items" on public.invoice_items
  for all using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Doctors see own items" on public.invoice_items
  for all using (
    exists (select 1 from public.invoices where id = invoice_items.invoice_id and doctor_id = auth.uid())
  );
